export const textConsts = {
  tushar: "Tushar",
  web: "Web",
  developer: "Developer",
  portfolio: "Portfolio",
  website: "Website",
  atSign: "@",
  copyright: "Copyright",
  by: "By",
  tech: "Tech",
  stacks: "Stacks",
  languages: "Languages",
  frameworks: "Frameworks",
  andSign: "&",
  library: "Library",
  version: "Version",
  control: "Control",
  platforms: "Platforms",
  IDE: "IDE",
  tools: "Tools",
  Education: "Education",
  Experience: "Experience",
};
