export const textConsts = {
  tushar: "Tushar",
  web: "Web",
  developer: "Developer",
  portfolio: "Portfolio",
  website: "Website",
  atSign: "@",
  copyright: "Copyright",
  by: "By",
  tech: "Tech",
  stacks: "Stacks",
  languages: "Languages",
  frameworks: "Frameworks",
  andSign: "&",
  library: "Library",
  version: "Version",
  control: "Control",
  platforms: "Platforms",
  IDE: "IDE",
  tools: "Tools",
  Education: "Education",
  Experience: "Experience",
  Senior: "Senior",
  Secondary: "Secondary",
  graduation: "Graduation",
  certifications: "Certifications",
  projects: "Projects",
  Socials: "Socials",
  meta: "Meta",
  front: "Front",
  end: "End",
};

export const years = {
  2016: "2016",
  2017: "2017",
  2018: "2018",
  2022: "2022",
};
